development:
  adapter: postgresql
  encoding: unicode
  database: altitude_backend_dev
  pool: 2
  username: nathan.wright
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: altitude_backend_test
  pool: 2
  username: nathan.wright
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: altitude_backend_production
  pool: 2
  username: nathan.wright
  password: