development:
  adapter: postgresql
  encoding: unicode
  database: altitude_backend_dev
  host: localhost
  pool: 2
  username: postgres
  password: soapui123

test:
  adapter: postgresql
  encoding: unicode
  database: altitude_backend_test
  host: localhost
  pool: 2
  username: postgres
  password: soapui123

production:
  adapter: postgresql
  encoding: unicode
  database: altitude_backend_production
  host: localhost
  pool: 2
  username: postgres
  password: soapui123
